on:
  - push
  - pull_request
permissions:
  contents: read
jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-11
          - ubuntu-22.04
          - windows-2019
        node-version:
          - 14
          - 16
          - 18
          - 20
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
